use super::{Rule, Severity};

pub fn all_rules() -> Vec<Rule> {
    vec![
        Rule {
            id: "SSC001",
            name: "AWS access key ID",
            pattern: r"AKIA[0-9A-Z]{16}",
            severity: Severity::Critical,
            min_entropy: Some(3.0),
        },
        Rule {
            id: "SSC002",
            name: "AWS secret access key",
            pattern: r#"(?i)aws[_\-\.]?secret[_\-\.]?(?:access[_\-\.]?)?key['\"=:\s]+([A-Za-z0-9/+=]{40})"#,
            severity: Severity::Critical,
            min_entropy: Some(4.0),
        },
        Rule {
            id: "SSC003",
            name: "GitHub personal access token (classic)",
            pattern: r"ghp_[A-Za-z0-9]{36}",
            severity: Severity::Critical,
            min_entropy: Some(3.5),
        },
        Rule {
            id: "SSC004",
            name: "GitHub fine-grained personal access token",
            pattern: r"github_pat_[A-Za-z0-9_]{82}",
            severity: Severity::Critical,
            min_entropy: Some(3.5),
        },
        Rule {
            id: "SSC005",
            name: "GitLab personal access token",
            pattern: r"glpat-[A-Za-z0-9-]{20}",
            severity: Severity::Critical,
            min_entropy: Some(3.5),
        },
        Rule {
            id: "SSC006",
            name: "Private key PEM header",
            pattern: r"-----BEGIN (?:RSA |EC |DSA |OPENSSH |ENCRYPTED )?PRIVATE KEY-----",
            severity: Severity::Critical,
            min_entropy: None,
        },
        Rule {
            id: "SSC007",
            name: "Stripe live secret key",
            pattern: r"sk_live_[A-Za-z0-9]{24,}",
            severity: Severity::Critical,
            min_entropy: Some(3.5),
        },
        Rule {
            id: "SSC008",
            name: "Stripe publishable live key",
            pattern: r"pk_live_[A-Za-z0-9]{24,}",
            severity: Severity::High,
            min_entropy: Some(3.5),
        },
        Rule {
            id: "SSC009",
            name: "Slack token",
            pattern: r"xox[baprs]-[0-9A-Za-z-]{10,}",
            severity: Severity::Critical,
            min_entropy: Some(3.5),
        },
        Rule {
            id: "SSC010",
            name: "Slack webhook URL",
            pattern: r"https://hooks\.slack\.com/services/T[A-Z0-9]+/B[A-Z0-9]+/[A-Za-z0-9]+",
            severity: Severity::High,
            min_entropy: Some(3.5),
        },
        Rule {
            id: "SSC011",
            name: "JWT token",
            pattern: r"eyJ[A-Za-z0-9_-]{10,}\.eyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]+",
            severity: Severity::High,
            min_entropy: Some(4.0),
        },
        Rule {
            id: "SSC012",
            name: "PostgreSQL connection string",
            pattern: r#"postgres(?:ql)?://[^:]+:[^@]+@[^\s"']+"#,
            severity: Severity::Critical,
            min_entropy: Some(3.0),
        },
        Rule {
            id: "SSC013",
            name: "MySQL connection string",
            pattern: r#"mysql://[^:]+:[^@]+@[^\s"']+"#,
            severity: Severity::Critical,
            min_entropy: Some(3.0),
        },
        Rule {
            id: "SSC014",
            name: "Generic password assignment",
            pattern: r#"(?i)(?:^|[\s,;])\bpassword\b\s*[=:]\s*['"]?([A-Za-z0-9!@#$%^&*()\-_=+]{8,})['"]?"#,
            severity: Severity::High,
            min_entropy: Some(3.5),
        },
        Rule {
            id: "SSC015",
            name: "Generic API key assignment",
            pattern: r#"(?i)(?:^|[\s,;])\bapi[_-]?key\b\s*[=:]\s*['"]?([A-Za-z0-9-_]{16,})['"]?"#,
            severity: Severity::High,
            min_entropy: Some(3.5),
        },
        Rule {
            id: "SSC016",
            name: "Generic secret assignment",
            pattern: r#"(?i)(?:^|[\s,;])\b(?:secret|token)\b\s*[=:]\s*['"]?([A-Za-z0-9-_+/]{16,})['"]?"#,
            severity: Severity::High,
            min_entropy: Some(4.0),
        },
        Rule {
            id: "SSC017",
            name: "Twilio account SID",
            pattern: r"AC[0-9a-f]{32}",
            severity: Severity::High,
            min_entropy: Some(3.5),
        },
        Rule {
            id: "SSC018",
            name: "Twilio auth token",
            pattern: r#"(?i)twilio.*auth.*token['"\s=:]+([0-9a-f]{32})"#,
            severity: Severity::Critical,
            min_entropy: Some(3.5),
        },
        Rule {
            id: "SSC019",
            name: "SendGrid API key",
            pattern: r"SG\.[A-Za-z0-9-_]{22}\.[A-Za-z0-9-_]{43}",
            severity: Severity::Critical,
            min_entropy: Some(4.0),
        },
        Rule {
            id: "SSC020",
            name: "npm authentication token",
            pattern: r"npm_[A-Za-z0-9]{36}",
            severity: Severity::Critical,
            min_entropy: Some(3.5),
        },
    ]
}
